version: '3.8'

services:
  app:
    image: link-shorten
    ports:
      - "9292:9292"
    environment:
      - PORT=${PORT}
      - APP_BASE_URL=${APP_BASE_URL}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_DATASOURCE_DRIVER=${SPRING_DATASOURCE_DRIVER}